### ISSUE TITLE
Trouble editing the template

### ISSUE THREAD

**Issue by BoomCorp** [BuckyMaler/Global#2]
Simply a noob trying to customize the [Global template](https://github.com/BuckyMaler/global) by [Bucky Maler](https://github.com/BuckyMaler)

At the moment im trying to edit the Hire Us button from the template into a link to my shop. 
I'd like that button, when clicked, to redirect to a url. 
I have succesfuly changed the name (Shop) and color (Red) of the button but cant succesfuly edit its function. Some attempts resulted in another undesired "Shop" button appearing but not working but no attempt got the desired button to change its behavior.

Another minor issue is in the Works section. I uploaded my own images but they are not centered in the circle "frames". 

Any help is welcome

**Comment by BuckyMaler** [comment]
In order to use the "Hire Us" button as a link you will need to change the button in the markup to an anchor tag. For example, `<a href="https://www.yourshop.com">Shop</a>`. In addition to that, you'll want to remove the following event handle from functions:

```
$('.cta').click(function(){

    var curActive = $('.side-nav').find('.is-active'),
        curPos = $('.side-nav').children().index(curActive),
        lastItem = $('.side-nav').children().length - 1,
        nextPos = lastItem;

    updateNavs(lastItem);
    updateContent(curPos, nextPos, lastItem);

  });
```

As for the images, I cannot debug that issue without being able to interact with the code myself. I suggest you take a look at the Sass.
